services:
  postgres:
    build:
      context: ./infra
      dockerfile: Dockerfile_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./infra/pgdata:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  user_service:
    build: ./user_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
  
  vector_service:
    build: ./vector_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8001:8001"
  
  nlp_service:
    build: ./nlp_service
    depends_on:
      - vector_service
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8002:8002"
  
  gateway_service:
    build: ./gateway_service
    depends_on:
      - user_service
      - vector_service
      - nlp_service
    environment:
      USER_SERVICE_URL: http://user_service:8000
      VECTOR_SERVICE_URL: http://vector_service:8001
      NLP_SERVICE_URL: http://nlp_service:8002
    ports:
      - "8003:8003"
  
  frontend_service:
    build: ./frontend
    depends_on:
      - gateway_service
      - user_service
    ports:
      - "8004:8004"