name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common tree
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker images
        run: sudo docker-compose -f docker-compose.yml build

      - name: Run Docker containers
        run: sudo docker-compose -f docker-compose.yml up -d

      - name: Wait for services
        run: |
          # wait up to 60s for service ports
          for i in {1..60}; do
            if curl -sS http://localhost:8000/ >/dev/null 2>&1 && curl -sS http://localhost:8001/ >/dev/null 2>&1; then
              echo "services are up"; break
            fi
            sleep 1
            echo "waiting..."
          done

      - name: Run Unit Tests (user_service)
        run: |
          sudo docker-compose run --rm user_service pytest tests/unit -q

      - name: Run Unit Tests (vector_service)
        run: |
          sudo docker-compose run --rm vector_service pytest tests/unit -q

      - name: Run Integration Tests
        run: |
          sudo docker-compose run --rm user_service pytest tests/integration -q
          sudo docker-compose run --rm vector_service pytest tests/integration -q

      - name: Run E2E Tests
        run: |
          sudo docker-compose run --rm vector_service pytest tests/e2e -q

      - name: Show logs on failure
        if: failure()
        run: |
          sudo docker-compose logs

      - name: Stop Docker containers
        run: sudo docker-compose -f docker-compose.yml down