name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose (if needed)
        run: docker compose version || sudo apt install docker-compose-plugin -y

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Run Docker containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services ready
        run: |
          echo "Waiting for services..."
          for i in {1..30}; do
            if curl -sSf http://localhost:8000/ >/dev/null && curl -sSf http://localhost:8001/ >/dev/null; then
              echo "Services are up"; break
            fi
            echo "waiting... ($i)"
            sleep 3
          done

      - name: Run Tests
        run: |
          echo "Tests:"
          docker-compose exec -T user_service bash -c "PYTHONPATH=/app pytest"
          docker-compose exec -T vector_service bash -c "PYTHONPATH=/app pytest"
          docker-compose exec -T nlp_service bash -c "PYTHONPATH=/app pytest"
          docker-compose exec -T gateway_service bash -c "PYTHONPATH=/app pytest"

      - name: Show logs on failure
        if: failure()
        run: |
          docker-compose logs

      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down